I admit, this is a hack. By default -ansi is used which causes __STRICT_ANSI__ to be defined which means __le64 is not defined in sys/types.h, but is it used later in another header files.  The error is below. At least k3b now compiles and links on AMD64.
If you have a better solution, speak now.

g++ -DHAVE_CONFIG_H -I../../k3b/dvd+rw-tools -I/data/development/sources/kde-3.5/extragear/multimedia/k3b/dvd+rw-tools -I../.. -DQT_THREAD_SUPPORT -D_REENTRANT -Wno-long-long -Wundef -ansi -D_XOPEN_SOURCE=500 -D_BSD_SOURCE -Wcast-align -Wconversion -Wchar-subscripts -Wall -W -Wpointer-arith -O2 -pipe -fno-reorder-blocks -fno-schedule-insns -fno-inline -Wformat-security -Wmissing-format-attribute -Wno-non-virtual-dtor -fno-exceptions -fno-check-new -fno-common -DQT_CLEAN_NAMESPACE -DQT_NO_ASCII_CAST -DQT_NO_STL -DQT_NO_COMPAT -DQT_NO_TRANSLATION -fvisibility=hidden -fvisibility-inlines-hidden -fvisibility=hidden -fvisibility-inlines-hidden -DQT_CLEAN_NAMESPACE -DQT_NO_ASCII_CAST -DQT_NO_STL -DQT_NO_COMPAT -DQT_NO_TRANSLATION -USTRICT_ANSI -c /data/development/sources/kde-3.5/extragear/multimedia/k3b/dvd+rw-tools/growisofs_mmc.cpp -o ../../k3b/dvd+rw-tools/growisofs_mmc.o -Wp,-MD,../../k3b/dvd+rw-tools/.deps/growisofs_mmc.TUo
/usr/include/linux/byteorder/little_endian.h:43: error: ‘__le64’ does not name a type
/usr/include/linux/byteorder/little_endian.h:47: error: expected ‘,’ or ‘...’ before ‘*’ token
/usr/include/linux/byteorder/little_endian.h: In function ‘__u64 __le64_to_cpup(int)’:
/usr/include/linux/byteorder/little_endian.h:49: error: ‘p’ was not declared in this scope
/usr/include/linux/byteorder/little_endian.h: At global scope:
/usr/include/linux/byteorder/little_endian.h:67: error: ‘__be64’ does not name a type
/usr/include/linux/byteorder/little_endian.h:71: error: expected ‘,’ or ‘...’ before ‘*’ token
/usr/include/linux/byteorder/little_endian.h: In function ‘__u64 __be64_to_cpup(int)’:
/usr/include/linux/byteorder/little_endian.h:73: error: ‘p’ was not declared in this scope

svn path=/trunk/extragear/multimedia/k3b/; revision=489115