Fix compile (gcc 4.0.2, KDE 3.5). Sincerely, I don't understand the reason of the #if 0 . Also I couldn't solve one issue in k3bprocess.h:
k3bsoxencoder.cpp:(.gnu.linkonce.t._ZN13K3bSoxProgram4scanERK7QString[K3bSoxProgram::scan(QString const&)]+0x14b): undefined reference to `K3bProcess::OutputCollector::OutputCollector(KProcess*)'
k3bsoxencoder.cpp:(.gnu.linkonce.t._ZN13K3bSoxProgram4scanERK7QString[K3bSoxProgram::scan(QString const&)]+0x19f): undefined reference to `vtable for K3bProcess::OutputCollector'
collect2: ld returned 1 exit status

svn path=/trunk/extragear/multimedia/k3b/; revision=462994